### ISSUE TITLE
User validation on fl_data

### ISSUE THREAD

**Issue by calz1** [ClimbsRocks/auto_ml#204]
Do you have an example of using feature learning?  I assumed I could just do feature_learning on the training dataset but I get an error like so when running it on the boston dataset:

> ml_predictor.train(df_train, feature_learning=True, fl_data=df_train)

```

Traceback (most recent call last):
  File "/home/data/.local/lib/python3.6/site-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'MEDV'
```

**Comment by ClimbsRocks** [comment]
You've got it! 

Just copy the df_train:

`ml_predictor.train(df_train, feature_learning=True, fl_data=df_train.copy())`

**Comment by ClimbsRocks** [comment]
This is super-not-user-friendly though, so thanks for filing this. I'd run into this when I was trying this out (I did the exact same thing). It was obvious for me since I know what auto_ml does under the hood, but I'll add in some checking/validation/user logging today so that others don't run into this same problem, or at least have a better idea what to do when they encounter it. 

Just so this is documented in case anyone else wanders here when they run into an issue: Deep Learning is, of course, most powerful when you have a lot of data, so trying it out on a toy dataset like Boston will show you the structure of how `feature_learning` works, but the results won't be representative- which I assume you already know :)

**Comment by ClimbsRocks** [comment]
Oh, and one last general piece of advice @calz1 : I try to make sure all the new features have test coverage, so you should be able to open up the test suite and find examples there. Peeking into test suites is my favorite way of finding "documentation" for all the projects out there that are poorly documented.

**Comment by calz1** [comment]
That worked!

Thanks for the tip about checking the tests. I see that instead of copying training data, you split it again to make fl_data. Does using a separate data set for training and feature learning help prevent a form of over-fitting?

**Comment by ClimbsRocks** [comment]
yeah- using the same data for both means that when we fit the gradient-boosted model, we're asking the feature_learning model to make predictions on it's own training data (which it's going to be really good at, of course). the gradient boosted model will then learn "wow, these features from the feature_learning model are really good! i'm gonna rely heavily on those and not the others". 

one of my favorite ways of checking for overfitting is to score the model on both the test data, and the training data, to see if the scores are noticeably different. If the training score is much better, there's probably some overfitting somewhere. 

deep learning in general is prone to overfitting (one of my next steps in auto_ml is to add in more regularization to make it more difficult for them to overfit), particularly on small datasets, so we just have to be extra careful when it's in the mix.

**Comment by calz1** [comment]
OK, that makes sense. Thought of two more related questions:

1. Is there a reason it has to use the basic gradient boosting and not an optional, more sophisticated one like XGBoost?
2. Is there a way to see the learned features or are they really just a bunch of weighted neurons by the point the feature importance scoring happens? I see them showing as feature_learning_1, feature_learning_2, etc.

I've got it training on an internal dataset that I got 90% training accuracy with in v.2.0.1.  It is already up to 97.9% accuracy on epoch 35 with feature_learning, but I'm using a copy() of the training set. I'm going to re-run with a 50-50 split of the training instead and see how that does.

**Comment by ClimbsRocks** [comment]
@calz1 

I love your questions!

1. You can still pass in any of the params you normally would with .train, including `model_names='XGBRegressor'`, or any other model name of your choice. I was using "gradient boosting" here to refer to LightGBM, XGBoost, or sklearn's implementation collectively, since it's likely one of the three that will end up being best. 

2. No, one of the huge drawbacks of neural nets is their complete lack of interpretability. It's a huge black box model that's really good at what it does, but can't explain it at all. I'm sure this will change in future years (and there have already been a few stabs at this with some academic papers), but nothing that's ready for a production-grade engineering solution. For a few other drawbacks of neural nets, see my answer: https://www.reddit.com/r/datascience/comments/65yl7x/do_most_data_scientists_in_the_business_world/dgecil9/

3. Yeah, that's totally overfitting. I'll try to ship the regularization soon. In the meantime, if you've got more data, use it! more data helps prevent overfitting. Or, one undocumented feature in auto_ml is that you can hit `Ctrl + C` in the middle of training to stop training where it is. It does fail sometimes, which is why it's an undocumented and not-officially-supported feature, but I use it pretty frequently. Hit it around the epoch you get to 90% accuracy, and see if that helps any. 

Thanks for the continued reports! Data like this helps me keep improving auto_ml.

**Comment by ClimbsRocks** [comment]
@calz1 : alright, the user validation is shipped, and i've added l2 regularization to all the layers. 

still won't prevent overfitting to a small dataset, but should at least make it slightly more difficult to overfit :)

let me know how it goes!

**Comment by calz1** [comment]
Cool! I will play around with this in the near future.

**Comment by calz1** [comment]
@ClimbsRocks That definitely helped. I'm testing spam detection on this data set I think you saw me trying before:

https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection

Overall, it is at 97.8% accuracy using feature learning plus DeepLearningClassifier, which beats my prior best run with XGBoost at 96.6%

**Comment by ClimbsRocks** [comment]
That's awesome- thanks for the update!
