### ISSUE TITLE
Issue with minor change to sample code gave error

### ISSUE THREAD

**Issue by redpoint13** [ClimbsRocks/auto_ml#210]
made a simple change to sample code from:
ml_predictor.train(df_train)
to:
ml_predictor.train(df_train, model_names=['DeepLearningRegressor'])

was returned error after training completed:
Traceback (most recent call last):
  File "C:\Users\redpo\projects\examples\auto-ml\auto_ml_Core_Functionality_Example.py", line 54, in <module>
    predictions = trained_model.predict(df_test)
  File "C:\python\envs\tf\lib\site-packages\sklearn\utils\metaestimators.py", line 54, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\python\envs\tf\lib\site-packages\sklearn\pipeline.py", line 327, in predict
    return self.steps[-1][-1].predict(Xt)
  File "C:\python\envs\tf\lib\site-packages\auto_ml\utils_model_training.py", line 306, in predict
    prediction = self.model.predict(X_predict)
AttributeError: 'str' object has no attribute 'predict'

**Comment by ClimbsRocks** [comment]
@redpoint13 Thanks for filing the issue!

Which version of auto_ml are you using? Try `pip install --upgrade auto_ml` to make sure you're running on the latest (I know this was a bug in a previous version, but I thought I fixed it in recent versions). 

A few other quick thoughts since you seem to be new here (and that means you're one of my target audiences!):

- If you put your code inside backticks (the key between tab and esc on a mac keyboard), it will automatically format itself a bit more readably, like so:
`ml_predictor.train(df_train)` to `ml_predictor.train(df_train, model_names=['DeepLearningRegressor'])` 
produces the error
```
Traceback (most recent call last):
File "C:\Users\redpo\projects\examples\auto-ml\auto_ml_Core_Functionality_Example.py", line 54, in 
predictions = trained_model.predict(df_test)
File "C:\python\envs\tf\lib\site-packages\sklearn\utils\metaestimators.py", line 54, in 
out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
File "C:\python\envs\tf\lib\site-packages\sklearn\pipeline.py", line 327, in predict
return self.steps[-1][-1].predict(Xt)
File "C:\python\envs\tf\lib\site-packages\auto_ml\utils_model_training.py", line 306, in predict
prediction = self.model.predict(X_predict)
AttributeError: 'str' object has no attribute 'predict'
```
- Python naming conventions tend to use no capital letters (including in file names/modules) unless you're creating a class (which you probably won't have to worry about if you're focusing on data stuff). 
- A full code example that someone can copy/paste into their environment and run to reproduce the error will get you really, really good response rates when filing issues! People love code that directly reproduces a bug. 
- As a quick workaround, the issue you're encountering is caused by saving the model. So you can probably just skip the model saving step, and your code will probably work. Or, send me the code that you're running and I'll dive into it more :)

Thanks again for using the project, and filing issues! Once we've figured out this one, please let me know anything else we can add to this project to make it more useful or easier to use for ya.

**Comment by redpoint13** [comment]
Huge thanks for the prompt response!  Here is my code.  I will attach files with the output.  Playing with it a bit more today, it was clear that the issue was with file loaded after the dill.  It works before.  

Here is the code:

```
"""Basic example of auto_ml's functionality."""

from auto_ml import Predictor
from auto_ml.utils import get_boston_dataset
import dill

# Load data
df_train, df_test = get_boston_dataset()

# Tell auto_ml which column is 'output'
# Also note columns that aren't purely numerical
# Examples include ['nlp', 'date', 'categorical', 'ignore']
column_descriptions = {
    'MEDV': 'output', 'CHAS': 'categorical'
}

"""
Available options for type_of_estimator are:
    - regressor
    - classifier
"""

ml_predictor = Predictor(type_of_estimator='regressor',
                         column_descriptions=column_descriptions)

"""
Available options for model_names are:
    - DeepLearningClassifier
    - DeepLearningRegressor
    - XGBClassifier
    - XGBRegressor
    - LGBMClassifer
    - LGBMRegressor
"""
ml_predictor.train(df_train, model_names='DeepLearningRegressor')

# Score the model on test data
test_score = ml_predictor.score(df_test, df_test.MEDV)

# auto_ml is specifically tuned for running in production
# It can get predictions on an individual row (passed in as a dictionary)
# A single prediction like this takes ~1 millisecond
# Here we will demonstrate saving the trained model, and loading it again
file_name = ml_predictor.save()

# dill is a drop-in replacement for pickle that handles functions better
with open(file_name, 'rb') as read_file:
    trained_model = dill.load(read_file)

# .predict and .predict_proba take in either:
# A pandas DataFrame
# A list of dictionaries
# A single dictionary (optimized for speed in production evironments)
predictions = trained_model.predict(df_test)
print(predictions)

```

[error_output.txt](https://github.com/ClimbsRocks/auto_ml/files/977646/error_output.txt)

**Comment by ClimbsRocks** [comment]
Ah, perfect! 

You're hitting an edge case of the API. To load a model that uses deep learning, you have to use a specific load_ml_model function. 

Replace 
```
with open(file_name, 'rb') as read_file:
    trained_model = dill.load(read_file)
```
with 
```
from auto_ml.utils_models import load_ml_model
trained_model = load_ml_model(file_name)
```
More explanation coming in a minute.

**Comment by ClimbsRocks** [comment]
1. Thanks for the code formatting!
2. Thanks for confirming versions. 
3. I'll update the example to be more clear
4. The `dill.load` method works fine until you start using deep learning. For the deep learning stuff, I created `auto_ml.utils_models.load_ml_model`, which handles the complexities associated with the deep learning models. It also works for all non-deep-learning models, and should be the default way of loading models now. I'd forgotten I still had the old version in the example. It still technically works, until you start playing with the cool stuff like deep learning or `feature_learning`, at which point it becomes wildly misleading. I'll fix the example(s) now!
5. Let me know if you have any other feedback/thoughts/usability notes/bugs as you use this!

**Comment by ClimbsRocks** [comment]
Just finished updating the docs and test suite to only show `load_ml_model` everywhere. Thanks for pointing this out! Feel free to reopen this issue if this doesn't actually fix your problem.
