### ISSUE TITLE
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by sameerpallav** [ClimbsRocks/auto_ml#222]
When I train with DeepLearningRegressor with  a 5k dataset everything works fine but when I do it on 50k dataset I get this error.
```
Caused by op u'dense_1/random_normal/RandomStandardNormal', defined at:
  File "salary_predict.py", line 38, in <module>
    ml_predictor.train(df_train, model_names=['DeepLearningRegressor'])
  File "/home/ubuntu/deeparted/auto_ml/predictor.py", line 471, in train
    self.trained_final_model = self.train_ml_estimator(estimator_names, self._scorer, X_df, y)
  File "/home/ubuntu/deeparted/auto_ml/predictor.py", line 674, in train_ml_estimator
    trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning)
  File "/home/ubuntu/deeparted/auto_ml/predictor.py", line 548, in fit_single_pipeline
    ppl.fit(X_df, y)
  File "/home/ubuntu/deeparted/auto_ml/utils_model_training.py", line 88, in fit
    self.model.fit(X_fit, y, callbacks=[early_stopping])
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/wrappers/scikit_learn.py", line 138, in fit
    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))
  File "/home/ubuntu/deeparted/auto_ml/utils_models.py", line 559, in make_deep_learning_model
    model.add(Dense(hidden_layers[0], input_dim=num_cols, kernel_initializer='normal', kernel_regularizer=regularizers.l2(0.01)))
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/models.py", line 433, in add
    layer(x)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/engine/topology.py", line 558, in __call__
    self.build(input_shapes[0])
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/layers/core.py", line 827, in build
    constraint=self.kernel_constraint)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/engine/topology.py", line 391, in add_weight
    weight = K.variable(initializer(shape), dtype=dtype, name=name)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/initializers.py", line 75, in __call__
    dtype=dtype, seed=self.seed)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3356, in random_normal
    dtype=dtype, seed=seed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/random_ops.py", line 76, in random_normal
    shape_tensor, dtype, seed=seed1, seed2=seed2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_random_ops.py", line 220, in _random_standard_normal
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2514, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
```

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[47302,1]
         [[Node: dense_1/random_normal/RandomStandardNormal = RandomStandardNormal[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=5687716, _device="/job:localhost/replica:0/task:0/gpu:0"](dense_1/random_normal/shape)]]

Tensorflow: Version: 1.1.0
Cuda: 8.0
Cudann: 5.1.10

System Config:
Im using P2 (p2.8xlarge)
8 NVIDIA K80 GPUs(192 GB)
64 vCPUs
732 GiB of host memory

Training:
batch_size: 50
Dataset size: 50k
No of columns: 4 (1 Output, 2 Categorical, 1 Float)

Github Issues:
https://github.com/tensorflow/tensorflow/issues/4735
https://github.com/tensorflow/tensorflow/issues/1355
and many more on github

None of this solved the issue. Can anyone help me on this.

**Comment by ClimbsRocks** [comment]
Thanks for filing the issue!

Some quick thoughts:
1. It looks like it's choking just trying to make the first input layer. This is the last point in auto_ml's code that's called before it goes into Keras and TF code:
```
File "/home/ubuntu/deeparted/auto_ml/utils_models.py", line 559, in make_deep_learning_model
    model.add(Dense(hidden_layers[0], input_dim=num_cols, kernel_initializer='normal', kernel_regularizer=regularizers.l2(0.01)))
```
2. It's using an input matrix that has 47,302 columns. Given that you said you have two categorical columns, it's highly likely that one of those categorical columns is highly-dimensional. When we one-hot-encode that column, it probably blows up the number of columns to the many tens-of-thousands. 

To work around this immediately, I'd recommend bucketing your categorical column into fewer buckets. Hopefully then the input matrix for the deep learning model will have fewer columns. That should also help increase model accuracy, because having 47k columns and only 50k rows will lead to a very high noise:signal ratio. 

That said, I'm still surprised to see that this box is crashing. I wonder if it's partly due to using GPUs. I haven't worked with them too much myself, but offhand I recall them being more memory limited. If possible, try using CPUs and see if it still has the same issue. 

Let me know how that goes! Thanks for filing the issue. Let me know if there's anything else that could be clearer, or if you have any fun ML ideas that aren't baked into auto_ml yet!

**Comment by ClimbsRocks** [comment]
And thanks for such a detailed issue report. That helps tremendously.

**Comment by sameerpallav** [comment]
Thanks for the suggestion, I'm trying to reduce the variables down but can't I tweak the feature selection or feature learning so that it can reduce the no of variables automatically?

**Comment by lelayf** [comment]
I'm fitting a DNNRegressor in a loop, doing 10-fold cv for a variety of hidden layers topologies and learning steps. Dataset is microscopic (170 records x 67 float features). I can't seem get past 12 iterations (120 models), despite attempting explicit del of model and some garbage collection. I'm running on python 3.5 / TF 1.1rc1 on a Mac with 16GB RAM, CPU only. 
https://gist.github.com/lelayf/241b9b84d6103f737d43e12e965d180d

**Comment by ClimbsRocks** [comment]
@lelayf 

Thanks for the gist! It looks like you're not using auto_ml anywhere, and the error is coming from TensorFlow itself. Unfortunately, I don't know nearly enough about tf to debug that one properly for ya, so I gotta refer you to the experts maintaining TF.

**Comment by ClimbsRocks** [comment]
@sameerpallav 
Great intuition on feature_selection. Unfortunately, I disabled it for feature_learning while deciding how to settle the debate of whether it should come before or after feature_learning. 

However, if you're just training up a DNNRegressor, and not using feature_learning, you should be able to use feature_selection just fine. 

Worth noting though that if you have a column that has 40k different categorical values for 50k rows, you'll probably get better signal by bucketing those categories together. Or, you might be able to pass them in as non-categorical data, or sometimes `nlp` (name fields make great nlp candidates). 

Regardless, let me know how it goes!

**Comment by sameerpallav** [comment]
Yes. I tried those things already, by modifying nlp to support the categorical columns but it gave bad accuracy. Then I ran feature learning=True but got the same error OOM. But when I ran feature selection the error vanished and I'm using it on 300k data now and its fast. But then the accuracy is not what I expect out of it. Note that I used feature selection without any bucketing/binning of my categorical data. Is there some params I play around with to increase the accuracy?

**Comment by sameerpallav** [comment]
To increase accuracy I tried feature learning with perform_feature_selection(enabled it in the code because deep learning never runs without perform_feature_selection). After training deep learning finishes and Gradient Boost finishes I get this error while scoring and thus the model doesn not save.
Traceback (most recent call last):
  File "salary_predict.py", line 47, in <module>
    test_score = ml_predictor.score(df_test, df_test.salary_float)
  File "/home/ubuntu/deeparted/auto_ml/predictor.py", line 1064, in score
    return self._scorer.score(self.trained_pipeline, X_test, y_test, self.took_log_of_y, advanced_scoring=advanced_scoring, verbose=verbose, name=self.name)
  File "/home/ubuntu/deeparted/auto_ml/utils_scoring.py", line 225, in score
    predictions = estimator.predict(X)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/sklearn/utils/metaestimators.py", line 54, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/sklearn/pipeline.py", line 326, in predict
    Xt = transform.transform(Xt)
  File "/home/ubuntu/deeparted/auto_ml/utils_model_training.py", line 322, in transform
    predicted_features = self.predict(X)
  File "/home/ubuntu/deeparted/auto_ml/utils_model_training.py", line 306, in predict
    prediction = self.model.predict(X_predict)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/engine/training.py", line 1567, in predict
    check_batch_axis=False)
  File "/home/ubuntu/deeparted/tensorflow/local/lib/python2.7/site-packages/keras/engine/training.py", line 139, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected dense_1_input to have shape (None, 15) but got array with shape (42876, 204171)

What is going wrong here because it seems one of the only way to get a better accuracy.

**Comment by ClimbsRocks** [comment]
Hi @sameerpallav : 

The last issue you ran into is likely due to the modifications made to the code to support feature_selection with feature_learning. I have a feeling there are one or two assumptions we made in the codebase because of this design decision, that you didn't modify when you manually edited auto_ml. 

That said, I still return back to the original recommendation of binning. If you have a column with 40k categories, the model's never going to learn much from that column. You're essentially throwing away all the signal in that column. At that point, you're left with just a single categorical column, and a single float column. That's not very much data to go off of to predict something, especially because categorical columns are oftentimes not super useful (so the remaining categorical column is likely not super helpful). 

Deep Learning, in particular, relies on using huge amounts of data, both in terms of rows and columns. So only having two columns of data means deep learning is likely not your best bet. A standard gradient boosted algorithm (what auto_ml uses by default) is likely more accurate with this problem. Gradient boosted algorithms tend to be best for most business problems, and are much more easily explainable. 

From here, this sounds not a ton like a modeling problem, and more like a data collection and feature engineering problem. Let me know if you run into any issues with auto_ml, and I'm happy to debug! I appreciate your thorough bug reports.

**Comment by sameerpallav** [comment]
I also tried binning, reduced the categorical variables considerably. For eg on a larger dataset of 300k no of unique variables
Category1: 2400
Category2: 3000
Continous Variable.
Managed to improve the accuracy by 7% through feature selection deep learning regressor as compared to XGBoost. However deep learning without feature selection throws this error.
![screen shot 2017-05-20 at 4 12 42 am](https://cloud.githubusercontent.com/assets/5029625/26436472/56c45270-4134-11e7-8d3a-fbf6ffd6264e.png)

To improve the accuracy further feature learning sounds like a good fit but it just won't work because of the above error. And since you have disabled feature_Selection with feature_learning we can't work around it. I'm not sure but if this is an auto_ml issue but deep learning for a larger dataset with binning  just doesn't work on p2.8xlarge machine which is kind of strange. Any thoughts on this? And for a quick fix is there a proper way to enable feature_selection with feature learning and comes before feature_learning for my usecase.

**Comment by sameerpallav** [comment]
As per choice of the deep learning model. Our final use-case if the following 
Dataset: 1 million
Category1: 6900
Category2: 8900
Category3: 2
Category4: 500
Continous: 3
Nlp: 2

Tried with a smaller dataset 300k and saw a 7% accuracy boost on deep learning(with feature_selection) than on XGB.

**Comment by ClimbsRocks** [comment]
Wow, 7% is a huge boost! Glad you found the right model for your problem. 

Still weird that it won't run on that large of an instance. My only thought is that it might be because of the large amount of memory used, and GPUs not playing nicely with that. Try running on a CPU-only box with a bunch of memory- I've run deep learning with tens of thousands of columns on much smaller machines (CPU only) in the past, so this is pretty confusing behavior from TensorFlow. 

I'll look into adding `feature_selection` back in for `feature_learning`. It'll probably be a late next week project- I've got a couple high priority things in flight already. 

If you want to work on a PR, the relevant parts to look are atll in `predictor.py`. 
In particular the areas around:
line 340
line 420. we'll probably need to pass the transformation pipeline (self.trained_transformation_pipeline) through self._consolidate_pipeline. That way we already handle all the feature selection and remove that step before we start adding in new features with feature_learning. i haven't thought through this yet, but to be safe, we'll probably also want to transform our combined_data on the transformation_pipeline once we've consolidated it. that way we know we're only passing the features that passed our feature selection step into the feature_learning model. that might be happening already though- just check to see the number of columns you have at that point, and make sure it's considerably fewer than what you started with. 

that might be it, but this is just me thinking through it for 30 seconds before rushing out the door, so there's likely something else i haven't thought of yet. Would love to see the PR if you make this change!

In the meantime, keep me posted on how things are going, and any other feedback you have!
