### ISSUE TITLE
AttributeError: grid_search_pipelines

### ISSUE THREAD

**Issue by volker48** [ClimbsRocks/auto_ml#226]
Received the following error when setting `perform_feature_selection=True`:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-d82d3b7c7032> in <module>()
----> 1 predictor.train(x_train, verbose=True, model_names=['LGBMRegressor'], perform_feature_selection=True)

/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in train(self, raw_training_data, user_input_func, optimize_final_model, write_gs_param_results_to_file, perform_feature_selection, verbose, X_test, y_test, ml_for_analytics, take_log_of_y, model_names, perform_feature_scaling, calibrate_final_model, _scorer, scoring, verify_features, training_params, grid_search_params, compare_all_models, cv, feature_learning, fl_data)
    485         del self.X_test
    486         del self.y_test
--> 487         del self.grid_search_pipelines
    488         del X_df
    489 

AttributeError: grid_search_pipelines

**Comment by ClimbsRocks** [comment]
hmmm... that one shouldn't be throwing an error. 

I don't have a test explicitly for that combination of params (`LGBM` and `perform_feature_selection=True`), but i've got several tests for each one individually, and all the tests pass. 

It looks like we don't use that attribute at all any more, so I'll delete the two references to it that we have, and this exact bug will be fixed. But I'm more concerned that this is a bug at all, because it should be covered by our test suite, and we've had plenty of people run with those parameters in the past. That inconsistency is worrying. 

Do you mind telling me which version of auto_ml you're using, and if you've made any modifications to the source code? 

Thanks again for filing issues! Super helpful.

**Comment by volker48** [comment]
pip freeze shows `auto-ml==2.1.7`. I just installed it this morning fresh from pypi and haven't changed the source at all. Let me know if you need anymore info to help debug.

**Comment by ClimbsRocks** [comment]
Thanks again for filing this. Should be fixed in v2.1.8 available on pip. Still quite perplexed where this error came from. Please keep me posted if you encounter anything else, whether bugs, or just usability questions! I'll be out of town this weekend, but pretty responsive once i'm back next week.
