### ISSUE TITLE
Update estimator default config

### ISSUE THREAD

**Issue by alejio** [ClimbsRocks/auto_ml#329]
In _utils_models.get_search_params_, the default _min_samples_split_ values for _RandomForestClassifier_ and _RandomForestRegressor_ should be always >1.

Current list _[1, 2, 5, 20, 50, 100]_ is responsible for cryptic exception in _ml_predictor.train_

**Comment by ClimbsRocks** [comment]
thanks for that! fixing that one now. i would have expected my test suite to get that, except in order to not make the tests take 4 hours, we truncate the grid search space, and the `1` value gets removed as part of that process. 

as a general fyi, if you're using a randomforest, then a gradientboosting algorithm is likely to be effective as well (possibly even more effective). my personal favorite gradient boosting implementation is microsoft's lightgbm, which we've integrated into auto_ml, and is easily installed with `pip install lightgbm` (though you may need to update your gcc compliler- on a mac that's `brew upgrade gcc`)

**Comment by ClimbsRocks** [comment]
should be fixed in the latest release. thanks for filing! let me know if you run into anything else.
