### ISSUE TITLE
A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

### ISSUE THREAD

**Issue by gbrian** [ClimbsRocks/auto_ml#346]
Hi,

Getting this error when running a classifier auto_ml.
Find all the details at https://github.com/gbrian/machinelearning_exercises/blob/master/ml/supervised/exercise_1/Exercise_1.ipynb

Thanks

**Comment by ClimbsRocks** [comment]
Very likely solved if you upgrade all your packages.

**Comment by ClimbsRocks** [comment]
sorry for the hasty response earlier. i was caught up in things for a while and wanted to give you a quick fix rather than just ignoring you. 

i'm going to assume this issue is closed, but please do let me know if it's not, or if you have any other feedback. i think i'll probably pin my versions soon so we don't run into issues like this again :)

**Comment by gbrian** [comment]
@ClimbsRocks soooorrry for late abswer!
No worries mate, your first answer was perfect.
I'll save you from the details but after blowing everything up and reinstalling all is working fine.
Thank you!
