### ISSUE TITLE
'RidgeClassifier' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by automaton8** [ClimbsRocks/auto_ml#61]
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'
while running test_script.py using
ml_predictor.train(training_data, optimize_entire_pipeline=True, optimize_final_model=True)

**Comment by ClimbsRocks** [comment]
awesome, thanks for filing! let me see what i can find. that might have been fixed in a series of improvements i've shipped, but i'll dig into it to verify.

**Comment by ClimbsRocks** [comment]
Hey @automaton8,

Thanks again for filing this! I've fixed this bug in one of the recent releases. I suspect that as one of our first users, I fixed this right after you downloaded the project, since it's a pretty fundamental bug that I dealt with pretty early on. 

Either way, if you pull the latest changes from master (or download v1.2.0 from pip), you'll find this is fixed, and a bunch of other things have been noticeably improved! Please keep the feedback rolling in. This project is pretty robust at this point, and tuned to be ready for production systems, but I'd love to hear more edge cases that I haven't run into yet and fix them! Or hear other ideas you have and put them on our roadmap. 

Warmly,
preston
